name: Bot Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar librerías
        run: pip install pyTelegramBotAPI

      - name: Ejecutar bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python bot.py
